version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nebus-test-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app_network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nebus-test-app_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - app

  db:
    image: postgres:latest
    container_name: nebus-test-app_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nebus_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2234
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgdata:
